# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on: [push, pull_request]

jobs:

  check-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

  build-and-deploy:
    needs: [check-and-test]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:

          - os: ubuntu-latest
            TARGET: arm

          - os: ubuntu-latest
            TARGET: arm64

          - os: ubuntu-latest
            TARGET: amd64

    steps:
      - name: Building ${{ matrix.TARGET }}
        run: echo "${{ matrix.TARGET }}"

      - uses: actions/checkout@master
      - name: Set up Go
      - uses: actions/setup-go@v3
        with:
          go-version: 1.17
          
      - name: Build
        run: GOOS=linux GOARCH=${{ matrix.TARGET }} go build -v -o nxs-backup-${{ matrix.TARGET }}

      - uses: actions/upload-artifact@v3
        with:
          name: nxs-backup-${{ matrix.TARGET }}
          path: nxs-backup-${{ matrix.TARGET }}

      - uses: softprops/action-gh-release@v1
        name: Upload binaries to release
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: nxs-backup-${{ matrix.TARGET }}
          prerelease: ${{ !startsWith(github.ref, 'refs/tags/') }}
